# rabbitmq, log_generator(node), log_receiver(node), mysql
version: '3.8'

services:
  log_generator:
    container_name: 'log_generator'
    image: node:18
    command: sh -c "npm i && npm run dev"
    ports: 
      - 3000:3000
    working_dir: /app
    volumes:
      - ./log_generator:/app
    environment:
      - TZ=Asia/Seoul
      - NODE_ENV=development
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_ID=admin
      - RABBITMQ_PASSWORD=admin
      - RABBITMQ_PORT=5672
      - MYSQL_HOST=mysql
      - MYSQL_PORT=8080
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=log
      - MYSQL_USER=sample
      - MYSQL_PASSWORD=sample
      # vhost 란? 각 유저마다 격리된 환경을 제공하는 기능. 
      # - RABBITMQ_VHOST=
    restart: unless-stopped  
    depends_on:
      - db
      - mq
  # log_consumer:
  #   container_name: 'log_consumer'
  #   image: node:18
  #   command: sh -c "npm i && npm run build && node dist/main.js"
  #   ports: 
  #     - 3333:3333
  #   working_dir: /app
  #   volumes:
  #     - ./log_consumer:/app
  #   environment:
  #     - TZ=Asia/Seoul
  #     - NODE_ENV=development
  #     - RABBITMQ_HOST=rabbitmq
  #     - RABBITMQ_ID=admin
  #     - RABBITMQ_PASSWORD=admin
  #     - RABBITMQ_PORT=5672
  #     - MYSQL_HOST=mysql
  #     - MYSQL_PORT=8080
  #     - MYSQL_ROOT_PASSWORD=root
  #     - MYSQL_DATABASE=log
  #     - MYSQL_USER=sample
  #     - MYSQL_PASSWORD=sample
  db:
    container_name: 'mysql'
    image: mysql:latest
    ports:
      - 8080:8080
    volumes:
      - ./db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=log
      - MYSQL_USER=sample
      - MYSQL_PASSWORD=sample
  mq:
    container_name: 'rabbitmq'
    image: rabbitmq:3.7.14-management-alpine
    ports:
      - 5672:5672
      - 15672:15672
      - 25672:25672
    volumes:
      - ./mq/lib:/var/lib/rabbitmq
      - ./mq/database:/var/lib/rabbitmq/mnesia/rabbit@my-rabbit
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
networks:
  big_size_log_project:
    external: true
  